name: Hello World Workflow
<<<<<<< HEAD

on:
  push:
    branches:
      - main  

jobs:
  greeting:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2  

    - name: Afficher Hello World
      run: echo "Hello World"  
=======
on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Display Hello World
      run: echo "Hello World"
>>>>>>> 211f4b10fdc7022e271fada4272725d3ec69cce9
